version: 1.1.{build}
configuration: Release
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    cd test/Preconditions.Tests/
    
    dotnet test
    
    cd ../..
after_test:
- ps: >-
    cd src/Preconditions
    
    nuget pack Preconditions.nuspec
    
    cd ../..
artifacts:
- path: '**\*.nupkg'
